# Generated by Django 5.0.2 on 2024-03-27 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0001_initial"),
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user_app.customer"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user_app.customer"
            ),
        ),
    ]
