# Generated by Django 5.0.2 on 2024-03-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_listed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('description', models.TextField()),
                ('image1', models.FileField(upload_to='media/product_image/')),
                ('image2', models.FileField(upload_to='media/product_images/')),
                ('image3', models.FileField(upload_to='media/product_images/')),
                ('image4', models.FileField(upload_to='media/product_images/')),
                ('image5', models.FileField(upload_to='media/product_images/')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.category')),
            ],
        ),
    ]
