# Generated by Django 5.0.2 on 2024-03-13 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('manufacturer_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image5',
        ),
        migrations.AddField(
            model_name='products',
            name='back_view_image',
            field=models.ImageField(null=True, upload_to='media/product_images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='main_image',
            field=models.ImageField(default=1, upload_to='media/product_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='side_view_image',
            field=models.ImageField(default=1, upload_to='media/product_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='brand_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_app.brand'),
            preserve_default=False,
        ),
    ]
