# Generated by Django 5.0.2 on 2024-03-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_brand_remove_products_image1_remove_products_image2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
