# Generated by Django 5.0.2 on 2024-03-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_cartproducts_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorimage',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
