# Generated by Django 5.0.2 on 2024-03-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_product_is_deleted_product_is_listed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
