# Generated by Django 5.0.2 on 2024-03-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_brand_is_deleted_brand_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='manufacturer_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='back_view_image',
            field=models.FileField(upload_to='media/product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.FileField(upload_to='media/product_image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='side_view_image',
            field=models.FileField(upload_to='media/product_images/'),
        ),
    ]
