# Generated by Django 5.0.2 on 2024-03-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0008_cartproducts_in_stock_productsize_in_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsize",
            name="quantity",
            field=models.PositiveBigIntegerField(),
        ),
    ]
