# Generated by Django 5.0.2 on 2024-03-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_rename_brand_id_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='back_view_image',
            field=models.FileField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.FileField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='side_view_image',
            field=models.FileField(upload_to='product_images/'),
        ),
    ]
