# Generated by Django 5.0.2 on 2024-03-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0010_orders_orderitem_delete_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="coupon",
        ),
    ]
