# Generated by Django 5.0.2 on 2024-03-15 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_alter_product_is_listed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='back_view_image',
            new_name='top_view_image',
        ),
        migrations.CreateModel(
            name='Product_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product')),
            ],
        ),
    ]
