# Generated by Django 5.0.2 on 2024-03-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('main_image', models.FileField(upload_to='product_variant_images/')),
                ('side_view_image', models.FileField(upload_to='product_variant_images/')),
                ('top_view_image', models.FileField(upload_to='product_variant_images/')),
                ('price', models.BigIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='admin_app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_Variant',
        ),
    ]
