# Generated by Django 5.0.2 on 2024-04-01 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0013_alter_orders_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="admin_app.payment"
            ),
        ),
    ]
