# Generated by Django 5.0.2 on 2024-04-03 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.productcolorimage'),
        ),
    ]
