# Generated by Django 5.0.2 on 2024-04-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0021_productcolorimage_in_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcolorimage",
            name="in_cart",
            field=models.BooleanField(default=False),
        ),
    ]
