# Generated by Django 5.0.2 on 2024-04-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0025_payment_failed_payment_pending_payment_success"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banner",
        ),
        migrations.DeleteModel(
            name="Coupon",
        ),
    ]
