# Generated by Django 5.0.2 on 2024-04-06 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_delete_banner_delete_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='placed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='admin_app.orders'),
        ),
    ]
