# Generated by Django 5.0.2 on 2024-04-06 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0027_orders_placed_at_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="payment",
            name="started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
