# Generated by Django 5.0.2 on 2024-04-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0028_payment_paid_at_payment_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(null=True),
        ),
    ]
