# Generated by Django 5.0.2 on 2024-04-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0032_rename_cancel_orderitem_cancel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='request_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='request_return',
            field=models.BooleanField(default=False),
        ),
    ]
