# Generated by Django 5.0.2 on 2024-04-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0033_orderitem_request_cancel_orderitem_request_return"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="request_cancel",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="request_return",
        ),
    ]
