# Generated by Django 5.0.2 on 2024-04-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0034_remove_orderitem_request_cancel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="order_status",
        ),
    ]
