# Generated by Django 5.0.2 on 2024-04-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0035_remove_orders_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="return_product",
        ),
    ]
