# Generated by Django 5.0.2 on 2024-04-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0038_alter_orders_razorpay_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="razorpay_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
