# Generated by Django 5.0.2 on 2024-04-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0039_alter_orders_razorpay_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="request_return",
            field=models.BooleanField(default=False),
        ),
    ]
