# Generated by Django 5.0.2 on 2024-04-09 04:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0042_productcolorimage_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcolorimage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
