# Generated by Django 5.0.2 on 2024-04-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0044_productoffer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoffer",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_app.productcolorimage",
            ),
        ),
    ]
