# Generated by Django 5.0.2 on 2024-04-13 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0050_alter_productoffer_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='product_color_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoffer', to='admin_app.productcolorimage'),
        ),
    ]
