# Generated by Django 5.0.2 on 2024-04-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0052_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.PositiveBigIntegerField(blank=True),
        ),
    ]
