# Generated by Django 5.0.2 on 2024-04-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0057_rename_coupon_coupon_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_applied',
            field=models.BooleanField(default=False),
        ),
    ]
