# Generated by Django 5.0.2 on 2024-04-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0065_alter_orderitem_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='money_deposit',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='money_withdrawn',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
