# Generated by Django 5.0.2 on 2024-04-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0070_alter_orders_discount_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
