# Generated by Django 5.0.2 on 2024-05-02 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0078_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='admin_app.productsize'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product_color_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsize', to='admin_app.productcolorimage'),
        ),
    ]
