# Generated by Django 5.0.2 on 2024-05-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0079_alter_orderitem_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsize",
            name="product_color_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_sizes",
                to="admin_app.productcolorimage",
            ),
        ),
    ]
