# Generated by Django 5.0.4 on 2024-05-08 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0084_delete_wallettransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "transaction_id",
                    models.CharField(
                        max_length=12, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "money_deposit",
                    models.PositiveBigIntegerField(blank=True, default=0),
                ),
                (
                    "money_withdrawn",
                    models.PositiveBigIntegerField(blank=True, default=0),
                ),
                ("time_of_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transaction",
                        to="admin_app.orders",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_app.wallet",
                    ),
                ),
            ],
        ),
    ]
