# Generated by Django 5.0.4 on 2024-05-08 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0085_wallettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_transaction",
                to="admin_app.orderitem",
            ),
        ),
    ]
