# Generated by Django 5.0.4 on 2024-05-09 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0086_wallettransaction_order_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="products",
        ),
        migrations.RemoveField(
            model_name="review",
            name="verified_purchase",
        ),
        migrations.AddField(
            model_name="review",
            name="product_color",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_app.productcolorimage",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.TextField(default=""),
        ),
    ]
