# Generated by Django 5.0.4 on 2024-05-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0087_remove_review_products_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banner",
        ),
    ]
