# Generated by Django 5.0.4 on 2024-05-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0089_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="banner_image",
            field=models.FileField(default="", upload_to=" banner_images/"),
        ),
    ]
