# Generated by Django 5.0.4 on 2024-05-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0090_banner_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
