# Generated by Django 5.0.4 on 2024-05-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0091_banner_is_listed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="banner_image",
            field=models.ImageField(default="", upload_to="banner_images/"),
        ),
    ]
