# Generated by Django 5.0.2 on 2024-04-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_video', models.FileField(upload_to='banner_images/')),
                ('target_id', models.IntegerField()),
                ('target_name', models.CharField()),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_listed', models.BooleanField()),
            ],
        ),
    ]
