# Generated by Django 5.0.2 on 2024-04-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(max_length=500),
        ),
    ]
